FROM ubi8/ubi:8.5

MAINTAINER chen chenzhan@ca.ibm.com

LABEL description="mode apache"

RUN yum -y install httpd &&     yum clean all

RUN echo "Hello from Containerfile" > /var/www/html/index.html

EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]
